name: uCombat
main: me.worddexe.uCombat.UCombat
version: 1.0
api-version: 1.21
author: worddexe
description: A comprehensive combat logging prevention plugin.
commands:
  ucombat:
    description: Main command for uCombat.
    usage: /ucombat [reload|status]
permissions:
  ucombat.bypass:
    description: Allows the player to bypass combat restrictions.
    default: op
  ucombat.admin:
    description: Grants access to admin commands of uCombat.
    default: op
